#!/bin/sh
echo "Sending blockchain status request to locally running SoldoCore"
wget -nv http://127.0.0.1:2276/xsrv?requestType=getBlockchainStatus -O response.json
echo "response.json content:"
cat response.json
rm response.json
echo ""
wget -nv https://localhost:2276/xsrv?requestType=getBlockchainStatus --no-check-certificate -O response_hs.json
echo "response_hs.json content:"
cat response_hs.json
rm response_hs.json
echo ""

